(add) new e-email text
slub/digas-fe-management pull request #52
Opened 2024-12-16 12:08 UTC by jehofmann

Add a new line in email to notify about outdated Internet Explorer.

2025-01-23 16:47 UTC, beatrycze-volk requested changes

2025-01-23 16:47 UTC, beatrycze-volk commented on Resources/Private/Language/de.locallang.xlf
> +			<trans-unit id="emailCreateUserConfirmationText5" approved="yes">
Why only those two? DIGAS works also with Chrome and probably most of the webrowsers. Maybe message should be something like:

`<![CDATA[Bei Verwendung des Internet Explorers als Standardbrowser kann es zu Problem kommen. Ist dies der Fall, ändern Sie bitte Webbrowser auf zB. Google Chrome, Microsoft Edge oder Mozilla Firefox, dann nutzen Sie bitte die Passwort-Vergessen-Funktion auf der DiGA.Sax Webseite.]]>`

2025-01-23 16:47 UTC, beatrycze-volk commented on Resources/Private/Language/locallang.xlf
> +				<source><![CDATA[Bitte verwenden Sie als Standardbrowser Microsoft Edge oder Mozilla Firefox. Bei Verwendung des Internet Explorers als Standardbrowser kann es zu Problem kommen. Ist dies der Fal
The source message should be in English. Probably something like this: 
`Problems may occur when using Internet Explorer as the default browser. If this is the case, please change your web browser to e.g. Google Chrome, Microsoft Edge or Mozilla Firefox, then please use the Forgot Password function on the DiGA.Sax website.`

2025-01-24 05:22 UTC, jehofmann commented on Resources/Private/Language/de.locallang.xlf
> +			<trans-unit id="emailCreateUserConfirmationText5" approved="yes">
The requirement and wording was given directly by the LfULG. It is only important to say that IE is no longer supported.

2025-01-24 05:24 UTC, jehofmann commented on Resources/Private/Language/locallang.xlf
> +				<source><![CDATA[Bitte verwenden Sie als Standardbrowser Microsoft Edge oder Mozilla Firefox. Bei Verwendung des Internet Explorers als Standardbrowser kann es zu Problem kommen. Ist dies der Fal
I followed the other entries and therefore assumed that it must also be written in German.

2025-01-24 09:05 UTC, beatrycze-volk commented on Resources/Private/Language/de.locallang.xlf
> +			<trans-unit id="emailCreateUserConfirmationText5" approved="yes">
Ok, then leave it as it is :)

2025-01-24 09:06 UTC, beatrycze-volk commented on Resources/Private/Language/locallang.xlf
> +				<source><![CDATA[Bitte verwenden Sie als Standardbrowser Microsoft Edge oder Mozilla Firefox. Bei Verwendung des Internet Explorers als Standardbrowser kann es zu Problem kommen. Ist dies der Fal
Actually it needs to be also corrected to other ones which are not written in English (some have already English text).

2025-01-24 09:07 UTC, jehofmann commented on Resources/Private/Language/locallang.xlf
> +				<source><![CDATA[Bitte verwenden Sie als Standardbrowser Microsoft Edge oder Mozilla Firefox. Bei Verwendung des Internet Explorers als Standardbrowser kann es zu Problem kommen. Ist dies der Fal
Good to know, I will fix them!

2025-01-24 16:01 UTC, beatrycze-volk approved these changes

2025-01-24 16:01 UTC, merged